name: pull version and change log from source

on:
  workflow_dispatch: # Manual trigger
  repository_dispatch: # Triggered by another repo if configured

jobs:
  sync-files:
    runs-on: ubuntu-latest
    steps:
      # Checkout the current repository
      - name: Checkout current repository
        uses: actions/checkout@v3

      # Clone the other repository
      - name: Clone source repository
        run: |
          git clone --depth 1 https://github.com/altfreq07/plugin.video.fenlight.git source-repo

      # Sync files
      - name: Sync files
        run: |
          rsync -av --delete source-repo/fen_light_changes source-repo/fen_light_version ./packages/

      # Remove the source-repo folder
      - name: Clean up source-repo folder
        run: |
          rm -rf source-repo

      # Commit changes
      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Sync version and changes from source repository" || echo "No changes to commit"

      # Push changes back to the repository
      - name: Push changes
        run: |
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
